const params = new URLSearchParams(location.search); const cursoId = params.get('curso');
let cursos=LMS.load('cursos'),modulos=LMS.load('modulos'),lecciones=LMS.load('lecciones');
const curso=cursos.find(c=>c.codigo===cursoId);const title=document.getElementById('tituloCurso'),modulosDiv=document.getElementById('modulos'),moduloForm=document.getElementById('moduloForm'),moduloNombre=document.getElementById('moduloNombre'),moduloSelect=document.getElementById('moduloSelect'),leccionForm=document.getElementById('leccionForm'),tituloLeccion=document.getElementById('tituloLeccion');let editModuloIndex=null;
if(!curso){title.textContent='Curso no encontrado';modulosDiv.innerHTML=LMS.emptyState('El curso solicitado no existe.');moduloForm.style.display='none';leccionForm.style.display='none';}else{title.textContent=curso.nombre;document.getElementById('cursoDescripcion').textContent=curso.descripcion||'Sin descripción';document.getElementById('cursoDocente').textContent=curso.docenteNombre||'Sin docente';document.getElementById('cursoCategoria').textContent=curso.categoria||'Sin categoría';}
function save(){LMS.save('modulos',modulos);LMS.save('lecciones',lecciones)}
function render(){if(!curso)return;const items=modulos.map((m,i)=>({m,i})).filter(x=>x.m.cursoCodigo===cursoId);modulosDiv.innerHTML=items.length?items.map(({m,i})=>{const ls=lecciones.filter(l=>l.cursoCodigo===cursoId&&l.moduloNombre===m.nombre);return `<article class="card moduleCard"><div class="moduleHeader"><div><span class="badge badge-primary">Módulo</span><h3>${LMS.escapeHTML(m.nombre)}</h3></div><div class="actions"><button class="btn-secondary" onclick="editarModulo(${i})">Editar</button><button class="btn-danger" onclick="eliminarModulo(${i})">Eliminar</button></div></div><ul class="lessonList">${ls.length?ls.map(l=>`<li><i class="fa-solid fa-circle-play"></i><span>${LMS.escapeHTML(l.titulo)}</span></li>`).join(''):'<li class="muted">No hay lecciones todavía.</li>'}</ul></article>`}).join(''):LMS.emptyState('Este curso todavía no tiene módulos.');moduloSelect.innerHTML='<option value="">Seleccionar módulo</option>'+items.map(({m})=>`<option value="${LMS.escapeHTML(m.nombre)}">${LMS.escapeHTML(m.nombre)}</option>`).join('');}
moduloForm.addEventListener('submit',e=>{e.preventDefault();const name=moduloNombre.value.trim();if(!name)return LMS.notify('Escribe el nombre del módulo.','error');if(modulos.some((m,i)=>m.cursoCodigo===cursoId&&LMS.normalize(m.nombre)===LMS.normalize(name)&&i!==editModuloIndex))return LMS.notify('Ya existe un módulo con ese nombre.','warning');if(editModuloIndex!==null){const old=modulos[editModuloIndex].nombre;modulos[editModuloIndex].nombre=name;lecciones=lecciones.map(l=>l.cursoCodigo===cursoId&&l.moduloNombre===old?{...l,moduloNombre:name}:l);editModuloIndex=null;LMS.notify('Módulo actualizado.')}else{modulos.push({cursoCodigo:cursoId,nombre:name});LMS.notify('Módulo creado.')}save();moduloForm.reset();render();});
function editarModulo(i){if(!modulos[i])return;moduloNombre.value=modulos[i].nombre;editModuloIndex=i;moduloNombre.focus();}function eliminarModulo(i){const m=modulos[i];if(!m)return;if(lecciones.some(l=>l.cursoCodigo===cursoId&&l.moduloNombre===m.nombre))return LMS.notify('Elimina o mueve sus lecciones antes de borrar el módulo.','warning');LMS.confirmAction(`¿Eliminar “${m.nombre}”?`,()=>{modulos.splice(i,1);save();render();LMS.notify('Módulo eliminado.');});}
leccionForm.addEventListener('submit',e=>{e.preventDefault();const mod=moduloSelect.value,t=tituloLeccion.value.trim();if(!mod||!t)return LMS.notify('Selecciona un módulo y escribe el título.','error');lecciones.push({cursoCodigo:cursoId,moduloNombre:mod,titulo:t,contenido:''});LMS.save('lecciones',lecciones);leccionForm.reset();render();LMS.notify('Lección creada.');});
render();
