let estudiantes = LMS.load('estudiantes');
const form = document.getElementById('estudiantesForm'); const tabla = document.getElementById('tablaestudiantes'); const buscar = document.getElementById('buscar');
const fields = ['identificacion','nombres','apellidos','genero','fechaNacimiento','direccion','telefono'].reduce((o,id)=>(o[id]=document.getElementById(id),o),{}); let editando = null;
form?.addEventListener('submit', e => { e.preventDefault(); const value = Object.fromEntries(Object.entries(fields).map(([k,el])=>[k,el.value.trim()])); if(Object.values(value).some(v=>!v)){LMS.notify('Completa todos los campos obligatorios.','error');return;} if(estudiantes.some((x,i)=>x.identificacion===value.identificacion && i!==editando)){LMS.notify('Ya existe un estudiante con esa identificación.','warning');return;} const item={...value,codigo:value.identificacion,nombre:`${value.nombres} ${value.apellidos}`}; if(editando!==null){estudiantes[editando]=item;editando=null;LMS.notify('Estudiante actualizado.')}else{estudiantes.push(item);LMS.notify('Estudiante registrado.')} LMS.save('estudiantes',estudiantes);form.reset();render(buscar?.value||'');});
function eliminar(i){const e=estudiantes[i];if(!e)return;const cursos=LMS.load('cursos');if(cursos.some(c=>c.estudianteCodigo===e.codigo)){LMS.notify('No se puede eliminar: el estudiante está asignado a un curso.','warning');return;}LMS.confirmAction(`¿Eliminar a ${e.nombre}?`,()=>{estudiantes.splice(i,1);LMS.save('estudiantes',estudiantes);render(buscar?.value||'');LMS.notify('Estudiante eliminado.');});}
function editar(i){const e=estudiantes[i];if(!e)return;Object.entries(fields).forEach(([k,el])=>el.value=e[k]||'');editando=i;window.scrollTo({top:0,behavior:'smooth'});}
buscar?.addEventListener('input',()=>render(buscar.value));
function render(filtro=''){if(!tabla)return;const q=LMS.normalize(filtro);const rows=estudiantes.map((e,i)=>({e,i})).filter(({e})=>LMS.normalize(`${e.nombres} ${e.apellidos} ${e.identificacion}`).includes(q));tabla.innerHTML=rows.length?rows.map(({e,i})=>`<tr><td>${LMS.escapeHTML(e.identificacion)}</td><td>${LMS.escapeHTML(e.nombres)}</td><td>${LMS.escapeHTML(e.apellidos)}</td><td>${LMS.escapeHTML(e.genero)}</td><td>${LMS.escapeHTML(e.fechaNacimiento)}</td><td>${LMS.escapeHTML(e.direccion)}</td><td>${LMS.escapeHTML(e.telefono)}</td><td class="actions"><button class="btn-secondary" onclick="editar(${i})">Editar</button><button class="btn-danger" onclick="eliminar(${i})">Eliminar</button></td></tr>`).join(''):`<tr><td colspan="8">${LMS.emptyState('No hay estudiantes que coincidan con la búsqueda.')}</td></tr>`;}
render();
