const login = document.getElementById('studentLogin');
const portal = document.getElementById('studentPortal');
let estudiante = JSON.parse(sessionStorage.getItem('estudianteActivo') || 'null');

function getInscripciones() {
  const all = LMS.load('inscripciones', {});
  if (Array.isArray(all)) return {};
  return all;
}
function saveInscripciones(data) { LMS.save('inscripciones', data); }
function progressKey(code) { return `progreso_${estudiante.codigo}_${code}`; }
function progress(code) { return LMS.load(progressKey(code), []); }
function setActiveStudent(e) { estudiante=e; sessionStorage.setItem('estudianteActivo', JSON.stringify(e)); login.style.display='none'; portal.style.display='block'; renderPortal(); }

login?.addEventListener('submit', e => { e.preventDefault(); const id=document.getElementById('studentId').value.trim(); const found=LMS.load('estudiantes').find(x=>x.identificacion===id); if(!found)return LMS.notify('No encontramos un estudiante con esa identificación.','error'); setActiveStudent(found); });
document.getElementById('studentLogout')?.addEventListener('click',()=>{sessionStorage.removeItem('estudianteActivo'); estudiante=null; portal.style.display='none'; login.style.display='block';});

function renderPortal() {
  if(!estudiante)return;
  document.getElementById('studentName').textContent=`${estudiante.nombres} ${estudiante.apellidos}`;
  const all=getInscripciones();
  let mine=all[estudiante.codigo] || [];
  if(!mine.length && LMS.load('misCursos').length){ mine=LMS.load('misCursos'); all[estudiante.codigo]=mine; saveInscripciones(all); }
  const cursos=LMS.load('cursos'), mods=LMS.load('modulos'), lessons=LMS.load('lecciones');
  const container=document.getElementById('misCursos');
  const cards=cursos.filter(c=>mine.includes(c.codigo)).map(c=>{const total=lessons.filter(l=>l.cursoCodigo===c.codigo).length, done=progress(c.codigo).length, pct=total?Math.round(done/total*100):0; const grade=LMS.load('calificaciones').filter(x=>x.estudianteCodigo===estudiante.codigo&&x.cursoCodigo===c.codigo).sort((a,b)=>new Date(b.fecha)-new Date(a.fecha))[0]; const certificado=done.length>=total&&total>0&&grade?.nota>=70; return `<article class="card studentCourse"><span class="badge badge-primary">${LMS.escapeHTML(c.categoria||'Curso')}</span><h3>${LMS.escapeHTML(c.nombre)}</h3><p>${LMS.escapeHTML(c.descripcion||'Sin descripción')}</p><div class="progressBar"><div class="progressFill" style="width:${pct}%"></div></div><div class="progressText"><span>${done}/${total} lecciones</span><strong>${pct}%</strong></div>${grade?`<p class="gradeLine"><i class="fa-solid fa-star"></i> Última nota: <strong>${grade.nota}%</strong></p>`:''}<div class="courseActions"><button onclick="abrirCursoEstudiante('${LMS.escapeHTML(c.codigo)}')">Continuar</button><button class="btn-outline" onclick="abrirEvaluacion('${LMS.escapeHTML(c.codigo)}')">Evaluación</button>${certificado?`<button class="btn-secondary" onclick="emitirCertificado('${LMS.escapeHTML(c.codigo)}')"><i class="fa-solid fa-award"></i> Certificado</button>`:''}</div></article>`}).join('');
  container.innerHTML=cards || LMS.emptyState('Todavía no tienes cursos inscritos. Explora el catálogo para comenzar.');
  renderEvaluaciones(); renderStats();
}
function renderStats(){const all=getInscripciones(), mine=all[estudiante.codigo]||[]; document.getElementById('studentCoursesCount').textContent=mine.length; const grades=LMS.load('calificaciones').filter(x=>x.estudianteCodigo===estudiante.codigo); document.getElementById('studentAvg').textContent=grades.length?`${Math.round(grades.reduce((s,x)=>s+x.nota,0)/grades.length)}%`:'—'; document.getElementById('studentCertificates').textContent=LMS.load('certificados').filter(x=>x.estudianteCodigo===estudiante.codigo).length;}
function abrirCursoEstudiante(code){localStorage.setItem('cursoSeleccionado',code);window.location.href=`../cursopublico.html?student=${encodeURIComponent(estudiante.codigo)}`;}
function abrirEvaluacion(code){const ev=LMS.load('evaluaciones').find(x=>x.cursoCodigo===code); if(!ev)return LMS.notify('Este curso todavía no tiene evaluación.','warning'); renderQuiz(ev);}
function renderEvaluaciones(){const box=document.getElementById('evaluacionesDisponibles');const all=getInscripciones(),mine=all[estudiante.codigo]||[];const ev=LMS.load('evaluaciones').filter(e=>mine.includes(e.cursoCodigo));box.innerHTML=ev.length?ev.map(e=>`<button class="evaluationLink" onclick="renderQuizById('${e.id}')"><span>${LMS.escapeHTML(e.titulo)}</span><small>${e.preguntas.length} preguntas</small></button>`).join(''):LMS.emptyState('No hay evaluaciones disponibles.');}
function renderQuizById(id){const ev=LMS.load('evaluaciones').find(x=>x.id===id);if(ev)renderQuiz(ev);}
function renderQuiz(ev){const box=document.getElementById('quizModal');box.classList.add('open');box.innerHTML=`<div class="quizPanel"><button class="modalClose" onclick="cerrarQuiz()">×</button><span class="badge badge-primary">Evaluación</span><h2>${LMS.escapeHTML(ev.titulo)}</h2><form id="quizForm">${ev.preguntas.map((p,i)=>`<fieldset class="quizQuestion"><legend>${i+1}. ${LMS.escapeHTML(p.texto)}</legend>${p.opciones.map((o,j)=>`<label><input type="radio" name="q${i}" value="${j}" required> ${LMS.escapeHTML(o)}</label>`).join('')}</fieldset>`).join('')}<button type="submit">Enviar evaluación</button></form></div>`;document.getElementById('quizForm').addEventListener('submit',e=>{e.preventDefault();let correct=0;ev.preguntas.forEach((p,i)=>{const v=Number(new FormData(e.target).get(`q${i}`));if(v===p.correcta)correct++;});const nota=Math.round(correct/ev.preguntas.length*100);const grades=LMS.load('calificaciones');const record={id:`CAL-${Date.now()}`,evaluacionId:ev.id,cursoCodigo:ev.cursoCodigo,estudianteCodigo:estudiante.codigo,nota,aciertos:correct,total:ev.preguntas.length,fecha:new Date().toISOString()};grades.push(record);LMS.save('calificaciones',grades);cerrarQuiz();LMS.notify(`Evaluación enviada: ${nota}%` ,nota>=70?'success':'warning');renderPortal();});}
function cerrarQuiz(){document.getElementById('quizModal')?.classList.remove('open');}
function emitirCertificado(code){const curso=LMS.load('cursos').find(c=>c.codigo===code);const lessons=LMS.load(`progreso_${estudiante.codigo}_${code}`);const grade=LMS.load('calificaciones').filter(x=>x.estudianteCodigo===estudiante.codigo&&x.cursoCodigo===code).sort((a,b)=>new Date(b.fecha)-new Date(a.fecha))[0];if(!curso||!grade||grade.nota<70||!lessons.length)return LMS.notify('Completa las lecciones y obtén mínimo 70% en la evaluación.','warning');const certs=LMS.load('certificados');let cert=certs.find(x=>x.estudianteCodigo===estudiante.codigo&&x.cursoCodigo===code);if(!cert){cert={id:`CERT-${Date.now()}`,estudianteCodigo:estudiante.codigo,cursoCodigo:code,fecha:new Date().toISOString(),nota:grade.nota};certs.push(cert);LMS.save('certificados',certs);}const w=window.open('','_blank');w.document.write(`<html><head><title>Certificado ${cert.id}</title><style>body{font-family:Arial;text-align:center;padding:80px;background:#f7f8fc;color:#172033}.certificate{background:#fff;border:8px double #4f46e5;padding:70px;max-width:800px;margin:auto}.name{font-size:38px;font-weight:800;color:#4f46e5}.course{font-size:28px;margin:25px}.code{color:#64748b}</style></head><body><div class="certificate"><p>CONSTANCIA DE FINALIZACIÓN</p><h1>LMS ABC</h1><p>Se certifica que</p><div class="name">${LMS.escapeHTML(estudiante.nombres+' '+estudiante.apellidos)}</div><p>ha completado satisfactoriamente el curso</p><div class="course">${LMS.escapeHTML(curso.nombre)}</div><p>con una calificación de <strong>${grade.nota}%</strong></p><p class="code">Certificado ${cert.id} · ${new Date(cert.fecha).toLocaleDateString('es-CO')}</p><script>window.print()<\/script></div></body></html>`);w.document.close();}
if(estudiante){login.style.display='none';portal.style.display='block';renderPortal();}
